=== solana-mobile/mobile-wallet-adapter-registry/wallet-schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://solanamobile.com/mwa-wallet-registry-v1-0.json",
    "title": "Mobile Wallet Adapter wallet registry entry",
    "description": "A wallet app supporting the Mobile Wallet Adapter protocol specification",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "minLength": 1,
            "pattern": "\\S"
        },
        "entity": {
            "type": "string",
            "minLength": 1,
            "pattern": "\\S"
        },
        "url": {
            "type": "string",
            "format": "uri"
        },
        "icon": {
            "type": "string",
            "format": "uri-reference"
        },
        "protocol_specification_version": {"enum": [ "1.0" ] },
        "android": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "string",
                    "pattern": "^([a-zA-Z][a-zA-Z0-9_]*\\.)+[a-zA-Z][a-zA-Z0-9_]*$"
                }
            },
            "required": [ "application_id" ]
        },
        "ios": {
            "$comment": "iOS schema is not yet implemented (as MWA support for iOS is not complete)",
            "type": "object",
            "not": true
        }
    },
    "oneOf": [
        { "required": ["android"] },
        { "required": ["ios"] }
    ],
    "required": [ "name", "entity", "url", "icon", "protocol_specification_version" ]
}

=== solana-mobile/mobile-wallet-adapter-registry/entries/espresso-android.json
{
  "name": "Espresso Cash",
  "entity": "Espresso Cash",
  "url": "https://www.espressocash.com/",
  "icon": "https://raw.githubusercontent.com/espresso-cash/espresso-cash-public/5ead4e3a5e6ceb8358cefae62f91f3394a41212f/packages/espressocash_app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png",
  "protocol_specification_version": "1.0",
  "android": {
    "application_id": "com.pleasecrypto.flutter"
  }
}
